"""UniVerse BASIC keyword data for completion and hover."""

KEYWORDS: dict[str, str] = {
    "ABORT": "Terminates program execution and returns to the command level.",
    "AND": "Logical AND operator.",
    "BEGIN": "Used with CASE or TRANSACTION.",
    "BREAK": "Enables or disables the break key.",
    "CALL": "Calls an external subroutine.",
    "CASE": "Defines a case in a BEGIN CASE block.",
    "CHAIN": "Transfers control to another program.",
    "CLEAR": "Clears all variables.",
    "CLEARDATA": "Clears the DATA stack.",
    "CLEARFILE": "Clears all records from a file.",
    "CLEARSELECT": "Clears an active select list.",
    "CLOSE": "Closes a previously opened file.",
    "CLOSESEQ": "Closes a sequential file.",
    "COMMIT": "Commits the current transaction.",
    "COMMON": "Declares variables shared between programs.",
    "CONTINUE": "Continues to the next iteration of a loop.",
    "CONVERT": "Converts characters in a string.",
    "CRT": "Displays output to the terminal.",
    "DATA": "Pushes data onto the DATA stack for INPUT.",
    "DEFFUN": "Declares an external function.",
    "DEL": "Deletes a field, value, or subvalue from a dynamic array.",
    "DELETE": "Deletes a record from a file.",
    "DIM": "Declares a dimensioned array.",
    "DISPLAY": "Displays output to the terminal.",
    "ECHO": "Enables or disables terminal echo.",
    "END": "Marks the end of a program, subroutine, or block.",
    "ENTER": "Transfers control to a subroutine without return.",
    "EQUATE": "Defines a named constant.",
    "EXECUTE": "Executes a UniVerse command.",
    "EXIT": "Exits from a loop.",
    "FIND": "Finds a value in a dynamic array.",
    "FINDSTR": "Finds a substring in a dynamic array.",
    "FLUSH": "Flushes the output buffer for a sequential file.",
    "FOR": "Begins a FOR/NEXT loop.",
    "FOOTING": "Sets the page footing for printed output.",
    "FUNCTION": "Defines a user function.",
    "GET": "Reads data from a device.",
    "GETLIST": "Retrieves a saved select list.",
    "GOSUB": "Branches to a local subroutine.",
    "GOTO": "Unconditional branch to a label.",
    "HEADING": "Sets the page heading for printed output.",
    "HUSH": "Suppresses or enables terminal output.",
    "IF": "Conditional execution.",
    "IN": "Used with LOCATE and FIND.",
    "INPUT": "Reads input from the terminal.",
    "INS": "Inserts a value into a dynamic array.",
    "LET": "Assigns a value to a variable (optional keyword).",
    "LOCATE": "Locates a value in a dynamic array.",
    "LOCK": "Locks a resource.",
    "LOOP": "Begins a LOOP/REPEAT block.",
    "MAT": "Matrix operations on dimensioned arrays.",
    "MATBUILD": "Builds a dynamic array from a dimensioned array.",
    "MATPARSE": "Parses a dynamic array into a dimensioned array.",
    "MATREAD": "Reads a record into a dimensioned array.",
    "MATWRITE": "Writes a dimensioned array as a record.",
    "NEXT": "Ends a FOR/NEXT loop.",
    "NOT": "Logical NOT operator.",
    "NULL": "No operation.",
    "ON": "Used with GOTO or GOSUB for computed branching.",
    "OPEN": "Opens a file for reading and writing.",
    "OPENPATH": "Opens a file by pathname.",
    "OPENSEQ": "Opens a file for sequential access.",
    "OR": "Logical OR operator.",
    "PAGE": "Advances to a new page in printed output.",
    "PERFORM": "Executes a UniVerse command (synonym for EXECUTE).",
    "PRECISION": "Sets the number of decimal places for calculations.",
    "PRINT": "Outputs data to the printer or terminal.",
    "PRINTER": "Controls the printer.",
    "PROCREAD": "Reads a line from the PROC input buffer.",
    "PROCWRITE": "Writes a line to the PROC output buffer.",
    "PROGRAM": "Declares the program name.",
    "PROMPT": "Sets the character displayed for INPUT prompts.",
    "READ": "Reads a record from a file.",
    "READBLK": "Reads a block from a sequential file.",
    "READLIST": "Reads a select list into a dynamic array.",
    "READNEXT": "Reads the next ID from a select list.",
    "READSEQ": "Reads a line from a sequential file.",
    "READT": "Reads a block from tape.",
    "RELEASE": "Releases record locks.",
    "REMOVE": "Removes a value from a dynamic array.",
    "REPEAT": "Ends a LOOP/REPEAT block.",
    "RETURN": "Returns from a GOSUB or subroutine.",
    "REWIND": "Rewinds a tape.",
    "ROLLBACK": "Rolls back the current transaction.",
    "SELECT": "Creates a select list of record IDs.",
    "SEND": "Sends data to a device.",
    "SLEEP": "Pauses execution for a specified number of seconds.",
    "STOP": "Terminates program execution.",
    "SUBROUTINE": "Declares an external subroutine.",
    "SWAP": "Swaps values of two variables.",
    "THEN": "Used with IF and file I/O statements.",
    "ELSE": "Used with IF and file I/O statements.",
    "TO": "Used with FOR, OPEN, and other statements.",
    "TPRINT": "Prints to a terminal.",
    "TRANSACTION": "Used with BEGIN/END TRANSACTION.",
    "UNLOCK": "Unlocks a resource.",
    "UNTIL": "Loop termination condition.",
    "WEOF": "Writes an end-of-file mark on tape.",
    "WEOFSEQ": "Writes an end-of-file mark on a sequential file.",
    "WHILE": "Loop continuation condition.",
    "WRITE": "Writes a record to a file.",
    "WRITEBLK": "Writes a block to a sequential file.",
    "WRITELIST": "Saves a select list.",
    "WRITESEQ": "Writes a line to a sequential file.",
    "WRITET": "Writes a block to tape.",
}

BUILTIN_FUNCTIONS: dict[str, str] = {
    "ABS": "ABS(expr) — Returns the absolute value.",
    "ALPHA": "ALPHA(expr) — Returns 1 if the string is purely alphabetic.",
    "ASCII": "ASCII(expr) — Converts an EBCDIC character to ASCII.",
    "CATS": "CATS(arr1, arr2) — Concatenates corresponding elements of two dynamic arrays.",
    "CHANGE": "CHANGE(str, old, new [,count [,start]]) — Replaces occurrences of a substring.",
    "CHAR": "CHAR(code) — Returns the character for an ASCII code.",
    "COL1": "COL1() — Returns the start position of the last FIELD extraction.",
    "COL2": "COL2() — Returns the end position of the last FIELD extraction.",
    "CONVERT": "CONVERT(old, new, str) — Converts characters (function form).",
    "COS": "COS(expr) — Returns the cosine.",
    "COUNT": "COUNT(str, substr) — Counts occurrences of a substring.",
    "DATE": "DATE() — Returns the internal date.",
    "DCOUNT": "DCOUNT(str, delim) — Counts delimited fields.",
    "DELETE": "DELETE(arr, f [,v [,sv]]) — Deletes a field/value/subvalue (function form).",
    "DOWNCASE": "DOWNCASE(str) — Converts to lowercase.",
    "DQUOTE": "DQUOTE(str) — Encloses string in double quotes.",
    "EBCDIC": "EBCDIC(expr) — Converts ASCII to EBCDIC.",
    "EREPLACE": "EREPLACE(str, old, new [,count [,start]]) — Enhanced replace.",
    "EXCHANGE": "EXCHANGE(str, x, y) — Exchanges characters.",
    "EXP": "EXP(expr) — Returns e raised to a power.",
    "EXTRACT": "EXTRACT(arr, f [,v [,sv]]) — Extracts a field/value/subvalue.",
    "FIELD": "FIELD(str, delim, occurrence [,count]) — Extracts a delimited field.",
    "FIELDSTORE": "FIELDSTORE(str, delim, start, count, new) — Replaces delimited fields.",
    "FMT": "FMT(expr, format) — Formats a value.",
    "FOLD": "FOLD(str, width) — Folds a string to a specified width.",
    "ICONV": "ICONV(str, conv) — Converts external data to internal format.",
    "INDEX": "INDEX(str, substr, occurrence) — Finds position of a substring.",
    "INMAT": "INMAT() — Returns the number of elements in the last MATREAD.",
    "INSERT": "INSERT(arr, f, v, sv, new) — Inserts into a dynamic array.",
    "INT": "INT(expr) — Returns the integer part.",
    "ITYPE": "ITYPE(dict_item) — Evaluates an I-type expression.",
    "LEN": "LEN(str) — Returns the string length.",
    "LENDP": "LENDP(str) — Returns the display length.",
    "LN": "LN(expr) — Returns the natural logarithm.",
    "LOWER": "LOWER(str) — Lowers system delimiters by one level.",
    "MATCHFIELD": "MATCHFIELD(str, pattern, field) — Returns the matching field of a pattern match.",
    "MOD": "MOD(dividend, divisor) — Returns the modulus.",
    "NEG": "NEG(expr) — Returns the negation.",
    "NOT": "NOT(expr) — Returns logical NOT.",
    "NUM": "NUM(expr) — Returns 1 if the value is numeric.",
    "OCONV": "OCONV(str, conv) — Converts internal data to external format.",
    "PWR": "PWR(base, exp) — Returns base raised to a power.",
    "RAISE": "RAISE(str) — Raises system delimiters by one level.",
    "REM": "REM(dividend, divisor) — Returns the remainder.",
    "REPLACE": "REPLACE(arr, f, v, sv, new) — Replaces in a dynamic array.",
    "RND": "RND(range) — Returns a random number.",
    "SEQ": "SEQ(char) — Returns the ASCII code for a character.",
    "SIN": "SIN(expr) — Returns the sine.",
    "SPACE": "SPACE(n) — Returns a string of n spaces.",
    "SPLICE": "SPLICE(arr1, delim, arr2) — Splices two dynamic arrays.",
    "SQRT": "SQRT(expr) — Returns the square root.",
    "SQUOTE": "SQUOTE(str) — Encloses string in single quotes.",
    "STATUS": "STATUS() — Returns the status of the last file I/O operation.",
    "STR": "STR(str, n) — Repeats a string n times.",
    "SUBSTRINGS": "SUBSTRINGS(arr, start, length) — Extracts substrings from array elements.",
    "SUM": "SUM(arr) — Sums the elements of a dynamic array.",
    "SYSTEM": "SYSTEM(n) — Returns system information.",
    "TAN": "TAN(expr) — Returns the tangent.",
    "TIME": "TIME() — Returns the internal time.",
    "TIMEDATE": "TIMEDATE() — Returns the current time and date string.",
    "TRIM": "TRIM(str [,char [,option]]) — Trims characters from a string.",
    "TRIMB": "TRIMB(str) — Trims trailing spaces.",
    "TRIMBS": "TRIMBS(arr) — Trims trailing spaces from array elements.",
    "TRIMF": "TRIMF(str) — Trims leading spaces.",
    "TRIMFS": "TRIMFS(arr) — Trims leading spaces from array elements.",
    "UPCASE": "UPCASE(str) — Converts to uppercase.",
    "XLATE": "XLATE(file, id, f, code) — Translates a file reference.",
}
